---
title: "Introduction to Shiny"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: simple
    highlight: monochrome
    
  
---

Scripts and slides for presentations on Shiny. The presentation and material have been adapted for many different uses-- hopefully yours is below!

--- 

## Slide decks

* June 2022 - NMFS R UG - [Using Shiny for better science communication](presentations/shiny-slides-nmfsrug.html)
* December 2020: [Live translation in Shiny, and using `{learnr}` to supercharge your code teaching](presentations/extraslides.html)

## Tutorials

The shinyoverview [repo](https://github.com/mcsiple/shinyoverview) contains tutorials for `{shiny}` applications. If there are exercises with solutions, they are in a subfolder called `sol/`. You can either clone the whole repo, or download the folder for a specific tutorial.

* [Basics of Shiny](https://github.com/mcsiple/shinyoverview/tree/main/01_basics)
* [How to get data in and out of `{shiny}`](https://github.com/mcsiple/shinyoverview/tree/main/02_dataindataout)
* [Live translation with `{shiny.i18n}`](https://github.com/mcsiple/shinyoverview/tree/main/03_translation)
* [Maps with Shiny and `{leaflet}`](https://github.com/mcsiple/shinyoverview/tree/main/0n_maps)
* [Intro to `{learnr}`](https://github.com/mcsiple/shinyoverview/tree/main/04_learnr)
* [Interactive plots in `{shiny}` with `{ggplotly}`](https://github.com/mcsiple/shinyoverview/tree/main/05_ggplotly)



---
## Setup

If you want to try out the app examples, install the following packages:

```{r eval=FALSE}
# Basics
library(tidyverse)
library(kableExtra) # nice tables

# Shiny
library(shiny)
library(shinythemes) # bootstrap themes

# Interactive plots
library(plotly) 

# Making tutorials
library(learnr) # interactive tutorials
# remotes::install_github("rstudio-education/gradethis")
library(gradethis)

# Visualizing reactivity
library(reactlog)
```

This talk will introduce Shiny and its glorious abilities, with the assumption that you have heard of Shiny but haven't necessarily used it yet. Because there are tons of great examples online, I have highlighted tools that I have found useful and fun. The talk structure will be, more or less:

1. The building blocks: basic `shiny` functionality
2. Getting data into and out of `shiny`
3. Lessons I learned during the app development process

These latter two sections are optional but materials are included for you to explore on your own:

4. Translating `shiny` apps using `{shiny.18n}`
5. Shiny as a teaching tool using `{learnr}` 

## Example apps

* [Novel-gazing](https://msiple.shinyapps.io/NovelGazingApp/) (for Goodreads users) 

* [Adopt Don't Shop](https://nsilbiger.shinyapps.io/AdoptDontShop/) (collaboration with Nyssa Silbiger)

* [Marine Mammal Bycatch Impacts Exploration Tool](https://msiple.shinyapps.io/mmrefpoints/) (Collaboration with The Ocean Modeling Forum's Marine Mammal Bycatch Working Group)